### ISSUE TITLE
Lab Report 1 Feedback

### ISSUE THREAD

**Issue by JIzabal** [williamheng89/cse-15l-lab-report#1]
Here is your feedback for Lab Report 1:

- [x] All relevant URLs written as markdown links
- [x] All relevant code examples written with backticks (```)
- [x] All screenshots correspond to the described steps
- [x] All titles of sections are formatted as headers or similar
- [x] Lab report is on its own page, not the index page
- [ ] Last example counts keystrokes and shows how to run remotely saving time
  - Fix the last step so that the command copies and runs the code on the remote server: Part 7 – Making Remote Running Even More Pleasant (this is from the lab in week 1) - Use what you’ve learned to come up with the most pleasant process you can for making a local edit to WhereAmI.java, then copying it to the remote server and running it.
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by williamheng89** [comment]
-- Last example counts keystrokes and shows how to run remotely saving time
I fixed this part.

**Comment by JIzabal** [comment]
Although you do count keystrokes, the commands used don't show how to run remotely. Currently your command logs in using `ssh`, copies a file in the remote server into the remote server, compiles one file, and then runs another. We want you to copy a file that's on your computer to the remote server, compile that same file you copied into the remote server, and then run that file that was compiled that's on the remote server. Look into how to use the `scp` command from Part 5 in Lab 1 to see how to copy files locally (i.e., from your computer) to the remote server (i.e., to the computer you log into through ssh). Once you do that, look into Part 7 in Lab 1 to see how you can run a command (e.g., `javac` and `java`) that will run on the remote server. The example shown in Part 7 of Lab 1 shows how to do this with `ls`. After you've figured this out, then try combining the above two steps through the help of semicolons. Look at the example with `cp` in Part 7 of Lab 1 to see how to do this. If you have any more questions, feel free to ask here! Once you're done submit a regrade request to get full credit.

**Comment by williamheng89** [comment]
Thanks for clarifying on my mistake. I just requested a regrade request and believe everything is correct now (keystrokes).

**Comment by JIzabal** [comment]
No problem and great work!
